### ISSUE TITLE
Add CI Lint & Test workflows and update README badges

### ISSUE THREAD

**Issue by cdorst** [baofinance/baoswap-ui#15]
Add Lint & Test "Actions" workflows

Change badge on README from https://github.com/Uniswap/uniswap-interface/actions?query=workflow%3ATests to https://github.com/baofinance/baoswap-ui-source/actions?query=workflow%3ATests

![image](https://user-images.githubusercontent.com/18475870/108157468-71250400-70a8-11eb-8cb1-7399fbb7c5ea.png)

**Comment by cdorst** [comment]
See PR #16 for proposed fix

**Comment by Baowolf** [comment]
Old issue. Deprecated.
