### ISSUE TITLE
Fix "Honeyswap Default" default token list

### ISSUE THREAD

**Issue by cdorst** [baofinance/baoswap-ui#17]
The default token list is "Honeyswap Default" until "Accept update" or "Update list" options are selected.
To fix: load the Baoswap v2.5.1 list by default in place of the Honeyswap v1.3.5 list

![image](https://user-images.githubusercontent.com/18475870/108219036-efaa9180-70fa-11eb-830b-775a346630ae.png)

Kudos to OatMan for finding the bug:
![image](https://user-images.githubusercontent.com/18475870/108219160-0d77f680-70fb-11eb-8cf1-a2dc5580e867.png)

**Comment by cdorst** [comment]
See PR #18 for fix

**Comment by Baowolf** [comment]
Old issue. Deprecated.
