### ISSUE TITLE
Mobile Logo

### ISSUE THREAD

**Issue by thebaoman** [baofinance/baoswap-ui#2]
Logo appears squished on mobile view
![Screenshot_20210216-181641_Vivaldi_1](https://user-images.githubusercontent.com/75694573/108098406-51aebc80-7051-11eb-90e1-3fc6acab757e.png)

**Comment by cdorst** [comment]
Hello @thebaoman I think we can remove this style here to fix:
https://github.com/baofinance/baoswap-ui-source/blob/da070829f6d5e40d3eec2a00fa76b1ffd95a585a/src/components/Header/index.tsx#L109-L113

![LogoBug](https://user-images.githubusercontent.com/18475870/108109189-2c24b180-7057-11eb-8b0e-1c8fbf57775d.gif)

See PR #3

**Comment by jondwillis** [comment]
another option if you're inclined: https://github.com/baofinance/baoswap-ui-source/pull/24

**Comment by Baowolf** [comment]
Old issue. Deprecated.
