### ISSUE TITLE
Receive WETH should be Receive WXDAI

### ISSUE THREAD

**Issue by hyeres** [baofinance/baoswap-ui#28]
When removing liquidity, and one of the tokens is xDai, "receive weth" is written below the removal, when I believe this should be "receive wxdai". See screenshot below.

<img width="449" alt="Screen Shot 2021-03-02 at 10 24 27 PM" src="https://user-images.githubusercontent.com/76754976/109717559-80c34300-7ba6-11eb-9227-dac67fea657e.png">

**Comment by cdorst** [comment]
https://github.com/baofinance/baoswap-ui/blob/da070829f6d5e40d3eec2a00fa76b1ffd95a585a/src/pages/RemoveLiquidity/index.tsx#L541
