### ISSUE TITLE
Change "Honeyswap" to "Baoswap" on /migrate/v1/:address page

### ISSUE THREAD

**Issue by cdorst** [baofinance/baoswap-ui#7]
![image](https://user-images.githubusercontent.com/18475870/108143148-c7844980-708c-11eb-8070-240de81dcd08.png)

Replace "Honeyswap" with "Baoswap" in `MigrateV1Exchange.tsx`

**Comment by cdorst** [comment]
See PR #8 for proposed fix

**Comment by Baowolf** [comment]
Issue resolved
